#!/usr/bin/perl
#
# Daniel Engel 2011
#
#
use warnings;
use strict;

use Env;
use DBI;
use MIME::Base64;
use feature ":5.10";

my $debug = 0;
my $dbfile="/usr/apps/data/zbot_linux.db";
my $request;

sub query {
	my $query = shift;
        my $dbh = DBI->connect("dbi:SQLite:dbname=".$dbfile,"","");
        my $res = $dbh->do($query);
        undef($dbh);
	return $res;
}

sub get_record {
    my $value = shift;

    my $dbh = DBI->connect("dbi:SQLite:dbname=".$dbfile,"","");
    my $res = $dbh->selectrow_hashref("select * from `ledger` where value = \"$value\"");
    return $res;

}

sub _itest {                                                                                            
    my ($author, $all) = @_;                                               
    my ($value) = split /[:\s]+/, $all, 1;                                               
    my $retval="[$value]";

    my $ref = get_record($value);
    if ($ref ne undef) {
        my %record = %{$ref};
        foreach my $key ( keys(%record) ) {
	    $retval .= "[$key = $record{$key}]";
        }
    } else {
	    $retval .= "[404]";
    }

    return $retval;

}

sub _learn {                                                                                            
    my ($author, $all) = @_;                                               
    my ($value, $meaning) = split /[:\s]+/, $all, 2;                                               
    if (( $value ) and ( $meaning )) {
        my $dbh = DBI->connect("dbi:SQLite:dbname=".$dbfile,"","");
        my $res = $dbh->do("insert into `ledger` (value, meaning, author, date) values ('$value', '$meaning', '$author', date('now'))");
        undef($dbh);
        if ( $res ) {
            return ("Defined $value = $meaning");
        } else {
            return ("Unable to define");
        }
    }
    return undef;
}

sub _append {                                                                                            
    my ($author, $all) = @_;                                               
    my ($value, $meaning) = split /[:\s]+/, $all, 2;                                               
    if (( $value ) and ( $meaning )) {
        my %record = %{$ref};
        my $dbh = DBI->connect("dbi:SQLite:dbname=".$dbfile,"","");
        my $res = $dbh->do("update `ledger` set meaning=(meaning || ' $meaning'\), date=date('now') where value='$value'");
        undef($dbh);
        if ( $res ) {
            my $ref = get_record($value);
            return ("Defined $value = $ref->{meaning} $meaning");
        } else {
            return ("Unable to define");
        }
    }
    return undef;
}

sub _retrieve {
    my ($author, $all) = @_;                                               
    my ($value, $rest) = split /[:\s]+/, $all, 2;                                               
    my $ret="uh?";

    my $dbh = DBI->connect("dbi:SQLite:dbname=".$dbfile,"","");

    my $res = $dbh->selectall_arrayref("select id,meaning from `ledger` where value = \"$value\"");

    if ( $res ) {
        foreach my $row (@$res) {
	    my ($id, $meaning) = @$row;
	    $ret = "$value = $meaning";
        }

        $dbh->do("update `ledger` set hits = hits + 1 where value = \"$value\"");

    }
    undef($dbh);

    return $ret;
}

sub _forget {
    my ($author, $all) = @_;                                               
    my ($value, $rest) = split /[:\s]+/, $all, 2;                                               
    my $ret="uh?";

    my $dbh = DBI->connect("dbi:SQLite:dbname=".$dbfile,"","");

    my $res = $dbh->selectall_arrayref("select id,locked from `ledger` where value = \"$value\"");

    if ( $res ) {
        foreach my $row (@$res) {
	    my ($id, $locked) = @$row;
	    if ($locked) {
		    $ret = "Unable to delete, record locked!";
	    } else {
		    $dbh->do("delete from `ledger` where value = \"$value\"");
		    $ret = "Record deleted!";

	    }
        }
    }
    undef($dbh);

    return $ret;
}

sub _lock {
    my ($author, $all) = @_;                                               
    my ($value, $rest) = split /[:\s]+/, $all, 2;                                               
    my $ret="uh?";

    my $dbh = DBI->connect("dbi:SQLite:dbname=".$dbfile,"","");

    my $res = $dbh->selectall_arrayref("select id,locked from `ledger` where value = \"$value\"");

    if ( $res ) {
        foreach my $row (@$res) {
	    my ($id, $locked) = @$row;
	    if ($locked) {
		    $ret = "Already locked!";
	    } else {
		    $dbh->do("update `ledger` set locked = 1 where value = \"$value\"");
		    $ret = "Record locked!";

	    }
        }
    }
    undef($dbh);

    return $ret;
}

sub _unlock {
    my ($author, $all) = @_;                                               
    my ($value, $rest) = split /[:\s]+/, $all, 2;                                               
    my $ret="uh?";

    my $dbh = DBI->connect("dbi:SQLite:dbname=".$dbfile,"","");

    my $res = $dbh->selectall_arrayref("select id,locked from `ledger` where value = \"$value\"");

    if ( $res ) {
        foreach my $row (@$res) {
	    my ($id, $locked) = @$row;
	    if ($locked) {
		    $dbh->do("update `ledger` set locked = 0 where value = \"$value\"");
		    $ret = "Record unlocked!";
	    } else {
		    $ret = "Not locked!";

	    }
        }
    }
    undef($dbh);

    return $ret;
}

#
# MAIN
#

# If ran as module, use env var.
if (exists $ENV{ZBOT_ARGS}) {
    $request = $ZBOT_ARGS;
} else {
    exit(0) if ($#ARGV != 0);

    my $payload = $ARGV[0];
    chomp($payload);

    $request = decode_base64($payload);

    print "Encoded: $payload \n" if $debug;
    print "Decoded: $request \n" if $debug;

}

chomp($request);

my ($author, $command, $rest) = split /[:\s]+/, $request, 3;

print "Author : $author\n"  if $debug;
print "Command: $command\n" if $debug;
print "Rest   : $rest\n"    if $debug;

my $out="broken";

given ($command) {
    when (/\!learn/)  { $out = _learn($author, $rest); }
    when (/\!append/) { $out = _append($author, $rest); }
    when (/\!forget/) { $out = _forget($author, $rest); }
    when (/\!lock/) { $out = _lock($author, $rest); }
    when (/\!unlock/) { $out = _unlock($author, $rest); }
    when (/\!itest/)  { $out = _itest($author, $rest); }
    when (/\?/)       { $out = _retrieve($author, $rest); }
    default           { $out = "Unknown command $command"; }
}

print $out;
