#!/usr/bin/perl
#
use warnings;
use strict;
use Env;
use File::Basename;

my $numArgs = $#ARGV + 1;

my $prog = basename(__FILE__);

my $output="Got $numArgs args: $prog ";

foreach my $argnum (0 .. $#ARGV) {

   $output .=  "[$ARGV[$argnum]]";

}
my $test="";
print "$output ($ZBOT_ARGS) {$test}\n";

